# 配置文件版本
version: "3"


# 管理的服务
services:

    spider_work:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${COMPOSE_IMAGE:-centos7-py3}:latest
        container_name: ${COMPOSE_CONTAINER:-spiderPy3}
        volumes:
            - ${HOST_WORK_DIR}:/root/work:rw
            - ${HOST_LOG_DIR}:/var/log/spider_py3:rw
        ports:
            - ${HOST_RESERVED_PORT:-8000}:8000/tcp
        working_dir: /root/work
        privileged: true
        logging:
            driver: json-file
            options:
                max-size: 200m
                max-file: "3"
        command: ["/usr/sbin/init"]
        restart: always
        networks:
            - front


networks:
    front:
        ipam:
            driver: default
