# 配置文件版本
version: "3"


# 管理的服务
services:

    spider_work:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${IMAGE:-centos7-py3}:latest
        container_name: ${CONTAINER:-spiderPy3}
        volumes:
            - ${WORKDIR}:/root/work:rw
            - ${LOGDIR}:/var/log:rw
        working_dir: /root/work
        privileged: true
        logging:
            driver: json-file
            options:
                max-size: 200m
                max-file: "3"
        command: ["/usr/sbin/init"]
        restart: always
        networks:
            - spider_work


networks:
    spider_work:
        ipam:
            driver: default
